# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-29 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190729_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.IntegerField(max_length=2, primary_key=True, serialize=False),
        ),
    ]
