# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-29 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190729_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
